### ISSUE TITLE
1000000000000 errors when trying to compile

### ISSUE THREAD

**Issue by BrianBergh** [demonixis/C3DE#8] opened 2018-12-12 20:13 UTC
A lot of missing files etc etc. I could not get anything to work, so many compile errors and missing files.

**Comment by BrianBergh** [comment] 2018-12-12 20:32
I am on Windows, i have installed the latest version of Monogame (even tried older versions), nothing works. I am a skilled developer, and ye i can tell you : There is a lot of missing "cs" files in the project! - Soz, please try to download the Git repo as zip (as i did), unzip it, and try opening any of the solutions, then you'd see all the missing files and complains from VS! :P

**Comment by demonixis** [comment] 2018-12-12 20:34
What target? Windows (DirectX) or Desktop (OpenGL)?

**Comment by demonixis** [comment] 2018-12-12 20:50
I can confirm that the DesktopGL target wasn't updated and had errors. It's fixed on master branch. However, if you use Windows it's not recommanded to use this target because of many shader limitations.

**Closed by demonixis** 2018-12-12 20:50 UTC
